# coding: utf-8

"""
    UltraCart Rest API V2

    This is the next generation UltraCart REST API...

    OpenAPI spec version: 2.0.0
    Contact: support@ultracart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ultracart
from ultracart.rest import ApiException
from ultracart.models.order_linked_shipment import OrderLinkedShipment


class TestOrderLinkedShipment(unittest.TestCase):
    """ OrderLinkedShipment unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderLinkedShipment(self):
        """
        Test OrderLinkedShipment
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = ultracart.models.order_linked_shipment.OrderLinkedShipment()
        pass


if __name__ == '__main__':
    unittest.main()
