# coding: utf-8

"""
    UltraCart Rest API V2

    UltraCart REST API Version 2

    OpenAPI spec version: 2.0.0
    Contact: support@ultracart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ultracart
from ultracart.rest import ApiException
from ultracart.models.order_channel_partner import OrderChannelPartner


class TestOrderChannelPartner(unittest.TestCase):
    """ OrderChannelPartner unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderChannelPartner(self):
        """
        Test OrderChannelPartner
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = ultracart.models.order_channel_partner.OrderChannelPartner()
        pass


if __name__ == '__main__':
    unittest.main()
