# coding: utf-8

"""
    UltraCart Rest API V2

    This is the next generation UltraCart REST API...

    OpenAPI spec version: 2.0.0
    Contact: support@ultracart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ultracart
from ultracart.rest import ApiException
from ultracart.models.cart_customer_profile_address import CartCustomerProfileAddress


class TestCartCustomerProfileAddress(unittest.TestCase):
    """ CartCustomerProfileAddress unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartCustomerProfileAddress(self):
        """
        Test CartCustomerProfileAddress
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = ultracart.models.cart_customer_profile_address.CartCustomerProfileAddress()
        pass


if __name__ == '__main__':
    unittest.main()
