# coding: utf-8

"""
    UltraCart Rest API V2

    UltraCart REST API Version 2  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@ultracart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConversationJoinRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'participant_language_iso_code': 'str'
    }

    attribute_map = {
        'participant_language_iso_code': 'participant_language_iso_code'
    }

    def __init__(self, participant_language_iso_code=None):  # noqa: E501
        """ConversationJoinRequest - a model defined in Swagger"""  # noqa: E501

        self._participant_language_iso_code = None
        self.discriminator = None

        if participant_language_iso_code is not None:
            self.participant_language_iso_code = participant_language_iso_code

    @property
    def participant_language_iso_code(self):
        """Gets the participant_language_iso_code of this ConversationJoinRequest.  # noqa: E501


        :return: The participant_language_iso_code of this ConversationJoinRequest.  # noqa: E501
        :rtype: str
        """
        return self._participant_language_iso_code

    @participant_language_iso_code.setter
    def participant_language_iso_code(self, participant_language_iso_code):
        """Sets the participant_language_iso_code of this ConversationJoinRequest.


        :param participant_language_iso_code: The participant_language_iso_code of this ConversationJoinRequest.  # noqa: E501
        :type: str
        """

        self._participant_language_iso_code = participant_language_iso_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConversationJoinRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConversationJoinRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
