# coding: utf-8

"""
    UltraCart Rest API V2

    UltraCart REST API Version 2  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@ultracart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConversationPbxCallCaller(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'caller_id': 'str',
        'city': 'str',
        'country': 'str',
        'phone_number': 'str',
        'state': 'str'
    }

    attribute_map = {
        'caller_id': 'caller_id',
        'city': 'city',
        'country': 'country',
        'phone_number': 'phone_number',
        'state': 'state'
    }

    def __init__(self, caller_id=None, city=None, country=None, phone_number=None, state=None):  # noqa: E501
        """ConversationPbxCallCaller - a model defined in Swagger"""  # noqa: E501

        self._caller_id = None
        self._city = None
        self._country = None
        self._phone_number = None
        self._state = None
        self.discriminator = None

        if caller_id is not None:
            self.caller_id = caller_id
        if city is not None:
            self.city = city
        if country is not None:
            self.country = country
        if phone_number is not None:
            self.phone_number = phone_number
        if state is not None:
            self.state = state

    @property
    def caller_id(self):
        """Gets the caller_id of this ConversationPbxCallCaller.  # noqa: E501

        Caller ID name if available  # noqa: E501

        :return: The caller_id of this ConversationPbxCallCaller.  # noqa: E501
        :rtype: str
        """
        return self._caller_id

    @caller_id.setter
    def caller_id(self, caller_id):
        """Sets the caller_id of this ConversationPbxCallCaller.

        Caller ID name if available  # noqa: E501

        :param caller_id: The caller_id of this ConversationPbxCallCaller.  # noqa: E501
        :type: str
        """

        self._caller_id = caller_id

    @property
    def city(self):
        """Gets the city of this ConversationPbxCallCaller.  # noqa: E501

        City associated with the phone number  # noqa: E501

        :return: The city of this ConversationPbxCallCaller.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this ConversationPbxCallCaller.

        City associated with the phone number  # noqa: E501

        :param city: The city of this ConversationPbxCallCaller.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def country(self):
        """Gets the country of this ConversationPbxCallCaller.  # noqa: E501

        Country associated with the phone number (ISO 3166-1 alpha-2)  # noqa: E501

        :return: The country of this ConversationPbxCallCaller.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this ConversationPbxCallCaller.

        Country associated with the phone number (ISO 3166-1 alpha-2)  # noqa: E501

        :param country: The country of this ConversationPbxCallCaller.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def phone_number(self):
        """Gets the phone_number of this ConversationPbxCallCaller.  # noqa: E501

        Phone number in E.164 format  # noqa: E501

        :return: The phone_number of this ConversationPbxCallCaller.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this ConversationPbxCallCaller.

        Phone number in E.164 format  # noqa: E501

        :param phone_number: The phone_number of this ConversationPbxCallCaller.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def state(self):
        """Gets the state of this ConversationPbxCallCaller.  # noqa: E501

        State or province associated with the phone number  # noqa: E501

        :return: The state of this ConversationPbxCallCaller.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ConversationPbxCallCaller.

        State or province associated with the phone number  # noqa: E501

        :param state: The state of this ConversationPbxCallCaller.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConversationPbxCallCaller, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConversationPbxCallCaller):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
