# coding: utf-8

"""
    UltraCart Rest API V2

    UltraCart REST API Version 2  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@ultracart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CustomerPricingTier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'pricing_tier_oid': 'int'
    }

    attribute_map = {
        'name': 'name',
        'pricing_tier_oid': 'pricing_tier_oid'
    }

    def __init__(self, name=None, pricing_tier_oid=None):  # noqa: E501
        """CustomerPricingTier - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._pricing_tier_oid = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if pricing_tier_oid is not None:
            self.pricing_tier_oid = pricing_tier_oid

    @property
    def name(self):
        """Gets the name of this CustomerPricingTier.  # noqa: E501

        Name  # noqa: E501

        :return: The name of this CustomerPricingTier.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomerPricingTier.

        Name  # noqa: E501

        :param name: The name of this CustomerPricingTier.  # noqa: E501
        :type: str
        """
        if name is not None and len(name) > 50:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `50`")  # noqa: E501

        self._name = name

    @property
    def pricing_tier_oid(self):
        """Gets the pricing_tier_oid of this CustomerPricingTier.  # noqa: E501

        Pricing Tier Oid  # noqa: E501

        :return: The pricing_tier_oid of this CustomerPricingTier.  # noqa: E501
        :rtype: int
        """
        return self._pricing_tier_oid

    @pricing_tier_oid.setter
    def pricing_tier_oid(self, pricing_tier_oid):
        """Sets the pricing_tier_oid of this CustomerPricingTier.

        Pricing Tier Oid  # noqa: E501

        :param pricing_tier_oid: The pricing_tier_oid of this CustomerPricingTier.  # noqa: E501
        :type: int
        """

        self._pricing_tier_oid = pricing_tier_oid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomerPricingTier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerPricingTier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
